- README.md
- spammers.txt
Explain that `example.com` also blocks `*.example.com`.
Remove duplicate `semalt.semalt.com` entry.
> Explain how subdomains work in README

- spammers.txt
I have been contacted by the webmaster of qitt.ru who was surprised to find his website here (saying that it had nothing to do with referrer spam), and asked it to be removed from the list. Since it was added in a "bulk" pull request, and since (IMO) the priority is to avoid mistakes (that could hurt real businesses, and that lower the credibility of this list), I'll be applying it ASAP.
I think it's a good time for us to move to a "peer-review-only" merge, i.e. merge only websites that have been reported/approved by at least 2 people. We should also document in the README that it's better to add one site at a time in pull request, we should avoid "bulk changes" because they are harder to validate.
> Remove qitt.ru

- spammers.txt
I was analyzing my unfiltered Google Analytics view. Every spam referrer was already on the list except this one (chinese-amezon.com).
> Added chinese-amezon.com

- spammers.txt
`seoanalyses.com` was reported in separate "bulk" pull requests, so I'm adding it in a single commit.
It was reported in #73 and #94. Another confirmation that this is a spammer domain can be found at http://observingreality.com/?p=157
> Add seoanalyses.com

- spammers.txt
I have seen this url pop up is some servers that I maintain, it is quite obviously a referrer spam domain, similar to get-free-traffic-now.com
> Added get-free-social-traffic.com

- spammers.txt
Both are redirected to typical SPAMmers:
free-floating-buttons.com --> http://sharebutton.to
hongfanji.com --> http://swipevault.com/invitation/?hop=wosinwu
> free-floating-buttons.com and hongfanji.com

- spammers.txt
Other pepople confiming this is spam referreal:
http://www.ohow.co/remove-copyrightclaims-org-referral-spam-google-analytics/
http://www.besttechtips.org/instructions-to-remove-copyrightclaims-org/
etc..
> Added copyrightclaims.org

- spammers.txt
The referring page does not mention my urls anywhere, they're only advertising their services.
[Screenshot](https://d.pr/i/1fIOx)
> Add wordpress-crew.net

- spammers.txt
Over 80% of traffic at a site in one day came from here. 100% bounce rate. The domain itself is used to buy/sell link referrals. Oddly this Libyan domain is registered in the UK:
Registrant:
x19 Limited
Ian Donovan
27 Old Gloucester Street
London
United Kingdom
Zip/Postal code: WC1N 3AX
contact@x19.biz
> Add adf.ly

- spammers.txt
Seen on site's analytics without any installed tracking code
> Add black-friday.ga

- spammers.txt
Ghost referral spam based on GA and web server logs
> Add hosting-tracker.com

- spammers.txt
Found in some of our clients' accounts. Already filtering this.
> Add fast-wordpress-start.com

- spammers.txt
Found in few Clients' accounts.
In GA forces hostname to google.com and redirects to Firefox plugin that in description mentions already known ilovevitaly.
> Add googlemare.com

- spammers.txt
New today, 92% of traffic on one website, 100% bounce rate. Website offer dubious money making scheme, registered on the 10 dec 2015.
> Adding traffic2cash.xyz

- spammers.txt
Started showing up in GA 2/21/16
Showing up as : http://go.ekatalog.xyz/
> Add ekatalog.xyz

- spammers.txt
Hit 3 diff GA accounts of mine starting on March 1st.
A lot of other complaints online about it
https://www.ohow.co/what-is-uptime-com-referral-in-google-analytics/
http://botcrawl.com/block-uptime-com-referral-in-google-analytics/
> Add uptime.com

- spammers.txt
Started showing up in GA March 20th.
Shows up as : wordpresscore.com
Other complaints about this domain:
https://blog.sucuri.net/2016/03/when-wordpress-plugin-goes-bad.html
http://betanews.com/2016/03/05/wordpress-plug-password-backdoor/
http://www.securityweek.com/backdoor-wordpress-plugin-steals-admin-credentials
http://news.softpedia.com/news/popular-wordpress-plugin-comes-with-a-backdoor-steals-site-admin-credentials-501383.shtml
https://www.youtube.com/watch?v=7hnJ1i9bIFo
Should be added and blocked ASAP to prevent malicious hacks/activity.
> Add wordpresscore.com

- spammers.txt
Adding `o-o-11-o-o.com`, a domain spamming several GA accounts I manage.
> Add o-o-11-o-o.com

- spammers.txt
This is just another domain of semalt.media which are known for referrer spam
> Adding free-video-tool.com

- spammers.txt
Started showing up in GA April 25th.
Shows up as "website-stealer-warning-alert.hdmoviecams.com"
> Add hdmoviecams.com

- spammers.txt
Adding `free-social-buttons7.xyz`, a domain spamming several GA accounts I manage.
Confirmed in, and closes #300.
> Add free-social-buttons7.xyz

- spammers.txt
Caused 80%+ of traffic on 3 websites. The seem to be trying a new trick by putting a unique code in the sub-domain, eg. 50455867.law-check-two.xyz to track who clicks on the link. Multiple redirects and intermediate websites try and give the impression that they are getting information from genuine governmental websites. Clearly a scam.
> Add law-check-two.xyz

- spammers.txt
New redirect domain to semalt (common known spammer). Appeared in my referral logs with usual query string containing my domain.
> Add top10-way.com

- spammers.txt
195.133.201.82 - - [30/Oct/2016:12:50:55 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. org" "Mozilla/8.0 (compatible; MSIE4.00; Windows 2003)"
195.133.201.82 - - [30/Oct/2016:16:47:35 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. org" "Mozilla/4.0 (compatible; MSIE6.00; Windows 2008)"
195.133.201.82 - - [30/Oct/2016:20:47:58 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. org" "Mozilla/3.0 (compatible; MSIE7.00; Windows 2008)"
195.133.201.82 - - [31/Oct/2016:00:45:11 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. org" "Mozilla/7.0 (compatible; MSIE4.00; Windows 2008)"
> Add aviav.org

- spammers.txt
193.124.131.27 - - [30/Oct/2016:12:50:56 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. ru.com" "Mozilla/4.0 (compatible; MSIE4.00; Windows 2003)"
193.124.131.27 - - [30/Oct/2016:16:47:35 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. ru.com" "Mozilla/6.0 (compatible; MSIE7.00; Windows 2007)"
193.124.131.27 - - [30/Oct/2016:20:41:56 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. ru.com" "Mozilla/7.0 (compatible; MSIE6.00; Windows 2008)"
193.124.131.27 - - [31/Oct/2016:00:32:39 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. ru.com" "Mozilla/7.0 (compatible; MSIE2.00; Windows 2007)"
> Add aviav.ru.com

- spammers.txt
185.158.113.14 - - [30/Oct/2016:20:33:20 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. info" "Mozilla/4.0 (compatible; MSIE3.00; Windows 2005)"
185.158.113.14 - - [31/Oct/2016:02:32:59 -0400] "HEAD / HTTP/1.1" 200 - "http:// aviav. info" "Mozilla/4.0 (compatible; MSIE4.00; Windows 2004)"
> Add aviav.info

- spammers.txt
134.249.74.95 - - [12/Nov/2016:18:14:40 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// electricwheelchairsarea. com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)"
134.249.74.95 - - [12/Nov/2016:18:14:41 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// electricwheelchairsarea. com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)"
134.249.74.95 - - [12/Nov/2016:18:14:41 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// electricwheelchairsarea. com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)"
> Add electricwheelchairsarea.com

- spammers.txt
added searchencrypt.com and scansafe.net to the blacklist
> Update spammers text with new domains

- spammers.txt
new referrer spam URL showing up in GA starting July 2 2017.
> Add autoseo-traffic.com

- spammers.txt
The following referrers were found in logs:
shymkent.xkaz.org
taraz.xkaz.org
Shymkent and Taraz are cities in Kazakhstan. The root site has links to multiple sites following the same pattern, which seem to all be porn sites.
> Add xkaz.org and all subdomains

- spammers.txt
Follows same pattern as https://github.com/piwik/referrer-spam-blacklist/pull/614, except with Russia instead of Kazakhstan.
> Add zrus.org and all subdomains

- spammers.txt
Found in WP Statistics logs. Blog about shopping for pretty much anything. Seems to be a legitimate site a first glance, but all of their amazon links have their own referral link. They are probably trying to promote their own site for profit through referral spam.
> Add shoppingmiracles.co.uk

- spammers.txt
adanih.com appears to be a site for free HD wallpapers.  However the full URL they spammed links to porn which includes child pornography.
> Add adanih.com

- spammers.txt
This "new-machina.html" referrer spammer hit my logs with 8 different domains.
Googling "new-machina.html" shows that a number of the results are obvious spamdexing sites.  Some are just replicated sites, using the same page layout/theme and many of the same images.
> Added homeafrikalike.tk

- spammers.txt
From the "new-machina.html" referrer spammer...  Domain is part of a group of spamdexing sites.
> Added livingroomdecoratingideas.website

- spammers.txt
Another one from the "new-machina.html" referrer spammer.  Domain is part of a network of spamdexing sites.
> Added mattgibson.us

- spammers.txt
The referrer links to a page under findercarphotos.com that contains links to 3D CG and hand drawn illustrations of child pornography.
> Added findercarphotos.com

- spammers.txt
Referrer originating from a completely unrelated site.  Googling "tora-home-design-reviews.html" used in the referrer URL shows a number of replicated spamdexing sites with the same page layout/theme, same awkward English text that sounds like a bad machine translation, as the site on freewlan.info.
> Added freewlan.info

- spammers.txt
Domain is part of a network of spamdexing sites that use "new-machina.html" as the destination page.  
(Edit: Fixed conflict)
> Added homemypicture.tk

- spammers.txt
"seocheckupx" referral appeared more than 30 times in a week on a website that usually has only 10-15 visits in the same timespan. It also uses the usual process of referral spammers, such as low number of pages visited and geographical origins essentially linked to Brazil / South America. The domain name itself is a clue, actually...
> Added seocheckupx.com to the list

- spammers.txt
complaint109505605.copyrightinstitute.org appeared in my Analytics.
It seems to be pointing to a Firefox add-on.
> Added copyrightinstitute.org

- spammers.txt
> Add med-dopomoga.com

- spammers.txt
> Add columb.net.ua

- spammers.txt
> Add hoztorg-opt.ru

- spammers.txt
> Add comp-pomosch.ru

- spammers.txt
> Add gandikapper.ru

- spammers.txt
> Add hyip-zanoza.me

- spammers.txt
We got a request from the owner of this website to remove it from the list.
It seems to be an online flower shop in Poland and unrelated to spam.
> Removes e-kwiaciarz.pl

- spammers.txt
get-more-freeer-visitors.info showed up in my GA reports last month. 20 users, 0 mins.
> Add get-more-freeer-visitors.info

- spammers.txt
> Add ww2awards.info

- spammers.txt
> Add computer-remont.ru

- spammers.txt
> Add russian-postindex.ru

- spammers.txt
> Add atleticpharm.org

- spammers.txt
> Add alkanfarma.org

- spammers.txt
> Add prostitutki-rostova.ru.com

- spammers.txt
> Add rybalka-opt.ru

- spammers.txt
Showing up in Google Analytics as referrer spam. Started in July 2018.
> Add punch.media

- spammers.txt
Showing up in Google Analytics as referrer spam. Started in July 2018.
> Add we-ping-for-youic.info

- spammers.txt
Flooded my Matomo referral statistics. Redirects to verytraffic.com which offers fake visitors stats.
> Add free-website-traffic.com

- spammers.txt
> Add gepatit-info.top

- spammers.txt
> Add undergroundcityphoto.com

- spammers.txt
> Add grafaman.ru

- spammers.txt
The actual spam referrer I saw was:
https://www.blogstar.fun/top-five-techniques-to-get-quick-visitors-to-site-and-make-money-quickly/50173724/
Blogstar.fun (both the full url above and the base domain) redirect to xtrafficplus.com
> Adds xtrafficplus.com, blogstar.fun

- spammers.txt
This domain (scammy online pharmacy) has been appearing in multiple sites' referer logs over the last few days. For example:
46.118.119.245 - - [22/Dec/2018:14:58:05 +0000] "GET / HTTP/1.1" 301 521 "http://kozhniebolezni.com/" "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 4.0; .NET CLR 1.0.2914)"
> Add kozhniebolezni.com

- spammers.txt
> Add porndl.org

- spammers.txt
> Add sel-hoz.com

- spammers.txt
Found in the logs of a German design freelancer. Dog site is not related in any way.
> Add doggyhealthy.com

- spammers.txt
> Add psn-card.ru

- spammers.txt
greatblog.top and xtrafficplus.com
> Added Referrer Spam

- spammers.txt
> Add gelstate.ru

- spammers.txt
> Add eropho.com

- spammers.txt
> Add lalalove.ru

- spammers.txt
Redirects to https://www.xtrafficplus.com/en/ via Google URL
> Add josephineblog.top

- spammers.txt
Minor issue, but otherwise converting it to a Go map errors out:
./blacklist.go:47:2: duplicate key "99-reasons-for-seo.com" in map literal
> Remove duplicate entry

- spammers.txt
axcus.top redirects to xtraffic.plus (a new domain of xtrafficplus.com, which is already in the blocklist).
> Add axcus.top and xtraffic.plus

- spammers.txt
artpress.top redirects to xtraffic.plus (a new domain of xtrafficplus.com, which is already in the blocklist).
> Add artpress.top

- spammers.txt
Redirects eventually to https://www.xtraffic.plus
> Add wallinside.top

- spammers.txt
Both redirect to xtraffic.plus (already in the blocklist).
> Add livejournal.top and posteezy.xyz

- spammers.txt
Redirects to xtraffic.plus (already in the blocklist).
> Add penzu.xyz

- spammers.txt
amylynnandrews.xyz redirects to xtraffic.plus (which is already in the blocklist).
> Block amylynnandrews.xyz

- spammers.txt
samlaurabrown.top redirects to xtraffic.plus (which is already in the blocklist).
> Block samlaurabrown.top

- spammers.txt
squarespace.top redirects to xtraffic.plus (which is already in the blocklist).
> Block squarespace.top

- spammers.txt
These redirects to xtraffic.plus (which is already in the blocklist).
> Block selfhotdog.com and thesensehousehotel.com

- spammers.txt
This redirects to xtraffic.plus (which is already in the blocklist).
> Block stylecaster.top

- spammers.txt
> Block jeffbullas.xyz

- spammers.txt
> Block hankspring.xyz

- spammers.txt
> Block matomete.net

- spammers.txt
> Block billyblog.online

- spammers.txt
> Block monicablog.xyz

- spammers.txt
> Block lawrenceblog.online

- spammers.txt
> Block carezi.com

- spammers.txt
> Block georgeblog.online

- spammers.txt
> Block samanthablog.online

- spammers.txt
I think everything ending with `.online` and `.top` is spam. I see the same pattern in email spam traffic.
> Add lindsayblog.online

- spammers.txt
> Add firstblog.top

- spammers.txt
Getting large amounts of "traffic" from bottraffic4free.club, saw that bottraffic4free.host was already added in the list where I've also gotten spam from. Both redirect to gammatraffic.com.
> Add bottraffic4free.club

- CONTRIBUTING.md
- README.md
- composer.json
refs https://github.com/matomo-org/referrer-spam-list/issues/1224
FYI we updated the name of the repo. The old repo name will still work and it won't break anything.
Creating this PR to adjust some links and docs.
Not sure how it would work to update a composer package without breaking anything. Maybe @sgiehl @Findus23 @kylerchin or someone else knows?
> Update new repository name referrer-spam-list

- spammers.txt
I have daily occurances of `umiq.prizesk.com` on my site. Other users, like in #1237 appear to see different sub-domains, so it probably makes sense to block `prizesk.com` completely.
Redirects to the already blocked `www.xtraffic.plus`.
> Add prizesk.com

- spammers.txt
Add own-ahrefs.com based on observations in my logs and https://www.abuseipdb.com/check/62.112.9.54 showing them as part of the semalt.com referral spammer.
> Added own-ahrefs.com (same spammer as semalt.com)

- spammers.txt
Saw a subdomain of it in my Matomo today, everything redirects to xtraffic.
> Add ahhjf.com, which redirects to xtraffic.plus.

- spammers.txt
Found subdomain spam on our site.
```
buctrk.fineblog.top 	1
rjvy.fineblog.top
```
> exclude fineblog.top

- spammers.txt
> Add sloopyjoes.com.top

- spammers.txt
The most common referrer to my academic website in 2020. Is not active anymore, but would be nice to have it filtered from my reports.
> trafficbot4free.xyz

- spammers.txt
> Add covblog.top

- spammers.txt
Since a few days, I see around 90 visitors a day from "advertisefree.co.uk". This is clearly fake traffic. Their website sells traffic to your website or something like that.
> Add advertisefree.co.uk

- spammers.txt
Redirects to https://www.xtraffic.plus/en/
> Add tourburlington.com

- spammers.txt
redirects to https://www.xtraffic.plus/en/
> Add figensahin.com

- spammers.txt
redirects to https://www.xtraffic.plus/en/
This one showed up today with multiple apparently randomized subdomains.
> add marihome.online

- spammers.txt
https://uniqgen.net/V2VvGm Gets redirected to random websites, this was added in one of the referral header attacks.
> Add uniqgen.net

- spammers.txt
Subdomain mnjd redirects to the blacklisted xtrafficplus.com
> Add lighthearteds.shop

- spammers.txt
Subdomains epbgw and lohmx redirects to the blacklisted xtrafficplus.com
> Add smzt.shop

- spammers.txt
All it has are links such as:
https[:]//livingsimply.com/living-simply/stretching-studios-are-popping-up-everywhere-are-they-worth-it/
https[:]//livingsimply.com/living-simply/14-things-to-know-before-you-unplug-and-stop-using-tech/
etc. etc.
> Add livingsimply.com

- spammers.txt
Found in my web tracking regularly but that site does not link to my website (ingo-steinke.de / ingo-steinke.com), not even in generic search results.
> Add topgurudeals.com

- spammers.txt
Redirects to blacklisted `xtraffic.plus`.
> Add maigralr.site

- spammers.txt
Adding rapidhits.net to the list.
Looks like my editor removed some extra whitespace, lmk if thats a problem and I can manually undo.
> Block rapidhits.net
