matomo-org/referrer-spam-list

spammers.txt
Registered a new domain and these spammers are on my referer list:
```
event-tracking.com
pornhub-forum.ga
pornhub-forum.uni.me
rapidgator-porn.ga
simple-share-buttons.com
youporn-forum.ga
```
=> Add more spammers

spammers.txt
These guys are our no.2 source of referral spam right now
=> add guardlink.org

spammers.txt
semaltmedia.com is the same semalt.com but advertised for video platform.
=> updated with semaltmedia.com

spammers.txt
dailyrank.net started showing sunday
=> dailyrank.net

spammers.txt
This is a little ironic ;)
Saw this spammer on Google Analytics
=> howtostopreferralspam.eu

spammers.txt
Looks like it's Semalt again (valid Hostname).
=> New addition: success-seo.com

spammers.txt
add referrer spam o-o-6-o-o.ru
=> add o-o-6-o-o.ru

spammers.txt
Saw this one on Google Analytics
=> fbdownloader.com

spammers.txt
Added video--production.com, part of Semalt
=> add video--production.com

spammers.txt
=> Add best-seo-software.xyz

spammers.txt
Found on 700+ of my clients accounts. makes a single visit and redirects to Aliexpress. A sister site of hongfanji.com.
=> Add rednise.com

spammers.txt
Appeared in my Piwik referrers and is a redirect to _semalt.com_
[Screenshot](https://frankl.in/u/IMG_8830.PNG) from Piwik Mobile
=> Add rankings-analytics.com

spammers.txt
New SPAM domain. Found in 37 Google Analytics accounts.
=> Add dbutton.net

spammers.txt
Found in 16 Google Analytics accounts, redirects to aliexpress.com
=> Add alibestsale.com

spammers.txt
=> Add pizza-imperia.com

spammers.txt
=> Add blogtotal.de

spammers.txt
Please add burger-imperia.com. Looks like referer spam.
=> Add burger-imperia.com

spammers.txt
traffic2money.com + yourserverisdown.com added to the list
=> Add yourserverisdown.com

spammers.txt
Confirmed referral spam based on my GA account and web server logs
=> Update for snip.to and get-your-social-buttons.info

spammers.txt
serw.clicksor.com/redir.php?url=<url> with and without www
=> Add clicksor.com

spammers.txt
Seen on site's analytics without installed tracking code
=> Add ranksonic.net

spammers.txt
Got some spam from these guys on my site.
=> Add o-o-8-o-o.com to spammers.txt

spammers.txt
=> Add santasgift.ml

spammers.txt
=> Add lsex.xyz

spammers.txt
=> Add rusexy.xyz

spammers.txt
As discussed in piwik/referrer-spam-blacklist#189
=> Add cyber-monday.ga

CONTRIBUTING.md
We are currently flooded by new additions, we need an easier way to manage them. We need to encourage people to open one pull request per new domain, and name PRs appropriately so that we can search them very easily (to find duplicates/confirmations).
Hopefully this guide will help. #97 could also help but someone needs to spend time doing it.
=> Add a CONTRIBUTING guide

README.md
I wanted to do this filtering in nginx because my server has many different services it proxies to, not all of them running the same language. I found it easier to do this in one place than throughout many different codebases.
=> Add nginx configuration instructions

spammers.txt
=> Add scripted.com

spammers.txt
Spamming out as website-stealer-warning.hdmoviecamera.net
+1
=> Added hdmoviecamera.net

spammers.txt
=> Add nufaq.com

spammers.txt
Found in few clients' accounts.
=> Add onlinetvseries.me

spammers.txt
Found in few clients' accounts.
=> Add uptimechecker.com

spammers.txt
Deleted 3rd level subdomains of 4 domains, switched to using their 2nd level parent instead. Cleaner list FTW.
=> Cleanup 7 subdomains

spammers.txt
=> Add for-your.website

spammers.txt
+1 started showing up in GA stats this morning
=> Added w3javascript.com

spammers.txt
=> Add trafficgenius.xyz

spammers.txt
Generates traffic from random subdomains.
=> Add snip.tw

spammers.txt
=> Add website-analyzer.info

spammers.txt
Found few days ago in multiple GA accounts.
=> Add share-buttons.xyz

spammers.txt
A lot of hits showing in GA this week.
=> Added traffic-cash.xyz

spammers.txt
This spammer has submitted several dozen requests using this referer on one account a few days ago. Not seen it on other accounts though.
=> Add social-widget.xyz

spammers.txt
Seeing this on 4 accounts since a circa a week
=> Add free-traffic.xyz

spammers.txt
Seeing referrer spam activity in GA this week from this domain.
=> Added web-revenue.xyz

spammers.txt
=> Added net-profits.xyz

spammers.txt
Showing up as 2085686.responsive-test.net
=> Add responsive-test.net

spammers.txt
Adding `rank-checker.online`, a domain spamming several GA accounts I manage.
=> Add rank-checker.online

spammers.txt
Started showing up in GA on Feb 28th.
=> Add site5.com

spammers.txt
Started showing up in GA March 21st and hitting every day.
Screenshot: http://i.imgur.com/boVBbEh.png
=> Add adtiger.tk

spammers.txt
This has been spamming our site
=> Adding getrichquick.ml

spammers.txt
Started showing up on April 19th
=> Add smartphonediscount.info

spammers.txt
Started showing up in GA April 4th
=> Add getrichquickly.info

spammers.txt
Started showing up in GA April 11th and 12th.
Screenshot: http://i.imgur.com/V9zmZHo.png
=> Add makeprogress.ga

spammers.txt
Appeared on my personal website with about 20 hits in a few minutes with a 100% bounce rate.
=> Add social-traffic-1.xyz

spammers.txt
Started showing up in GA May 4th
=> Add marketland.ml

spammers.txt
Appeared on my personal website with about 20 hits in a few minutes with a 100% bounce rate.
=> Add social-traffic-7.xyz

spammers.txt
Showing up as "forum.topic74207101.6hopping.com" .
=> Add 6hopping.com

spammers.txt
Started showing up in GA on Feb 27th
=> Add domain-tracker.com

spammers.txt
=> Add social-button.xyz

spammers.txt
=> Add socialbuttons.xyz

spammers.txt
Started showing up in GA April 13th - April 15th.
=> Add boostmyppc.com

spammers.txt
=> Adds pornogig.com

spammers.txt
Started showing up in GA May 8th and 9th.
=> Add topquality.cf

spammers.txt
Started showing up in GA April 28th
=> Add increasewwwtraffic.info

spammers.txt
Adding social-traffic-4.xyz, a domain spamming several GA accounts I manage.
=> Add social-traffic-4.xyz

spammers.txt
Adding `social-traffic-5.xyz`, a domain spamming several GA accounts I manage.
=> Add social-traffic-5.xyz

spammers.txt
=> Add social-traffic-2.xyz

spammers.txt
=> Add keywords-monitoring-success.com

spammers.txt
Found in the log files of website of a mathematics french tutor.
=> Add meds-online24.com

spammers.txt
Found in the log files of a mathematics french tutor.
=> Add supervesti.ru

spammers.txt
=> Add woman-orgasm.ru

spammers.txt
Started showing up in GA May 27th.
=> Add magicdiet.gq

spammers.txt
Showing up in referrer spam honeypot.
=> Add popads.net

spammers.txt
Started showing up in a referrer spam honeypot that I have setup.
=> Add unpredictable.ga

spammers.txt
Started showing up in a referrer spam honeypot that I have setup
=> Add ownshop.cf

spammers.txt
Started showing up in a referrer spam honeypot I have setup.
=> Add eu-cookie-law-enforcement2.xyz

spammers.txt
Started showing up in a honeypot I have setup.
=> Add cookie-law-enforcement-dd.xyz

spammers.txt
Started showing up in GA May 26th on a lawyer related website.
=> Add burn-fat.ga

spammers.txt
=> Add sexsaoy.com

spammers.txt
Found in the log files of a website of a mathematics french tutor.
=> Add pornoklad.ru

spammers.txt
An online shopping website found in the log files of a website of a mathematics french tutor.
=> Add mosrif.ru

spammers.txt
A website selling medical products found in the log files of a mathematics french tutor.
=> Add varikozok.ru

spammers.txt
A russian website about building materials found in the log files of a website of a mathematics french tutor.
=> Add sad-torg.com.ua

spammers.txt
Started showing up in GA May 13th.
=> Add easycommerce.cf

spammers.txt
Showing up in referrer spam honeypot.
=> Add online-templatestore.com

spammers.txt
Showing up in referrer spam honeypot.
=> Add zoominfo.com

spammers.txt
Started showing up in GA May 17th.
=> Add dominateforex.ml

spammers.txt
=> Add getlamborghini.ga

spammers.txt
Showing up in referrer spam honeypot.
=> Add monetizationking.net

spammers.txt
=> Add azlex.uz

spammers.txt
=> Add freenode.info

spammers.txt
=> Add zvetki.ru

spammers.txt
=> Add havepussy.com

spammers.txt
Starting showing up in a referrer spam honey pot.
=> Add fix-website-errors.com

spammers.txt
=> Add vesnatehno.com

spammers.txt
=> Add djonwatch.ru

spammers.txt
=> Add call-of-duty.info

spammers.txt
=> Add solitaire-game.ru

spammers.txt
=> Add replica-watch.ru

spammers.txt
=> Add buy-cheap-pills-order-online.com

spammers.txt
Started showing up in GA March 9th.
Screenshot: http://i.imgur.com/eDVism8.png
=> Add dogsrun.net

spammers.txt
=> Add moneytop.ru

spammers.txt
Showing up in GA and referrer spam honeypot.
=> Add law-enforcement-bot-ff.xyz

spammers.txt
Showing up in Google Analytics referrer spam honey pot.
=> Add site-auditor.online

spammers.txt
Showing up in my referrer spam honeypot.
Displaying as forum.topic25265461.ilovevitaly.xyz
=> Add ilovevitaly.xyz

spammers.txt
=> Add rumamba.com

spammers.txt
Showing up in referrer spam honey pot.
=> Add law-enforcement-ee.xyz

spammers.txt
=> Add legalrc.biz

spammers.txt
=> Add pron.pro

spammers.txt
=> Added seo-2-0.com

spammers.txt
=> Add wallpaperdesk.info

spammers.txt
Hit in GA referrer spam honey pot
=> Add social-buttons-ii.xyz

spammers.txt
Domain registered on 2016-06-30; hit 25 times my website yesterday.
=> Add law-six.xyz

spammers.txt
Request from hunterkreie 
referrer spam
=> Add works.if.ua

spammers.txt
Showing up in Google Analytics starting on August 19th.
=> Add 1-free-share-buttons.com

spammers.txt
Showing up in GA starting in Aug 15th
=> Add spin2016.cf

spammers.txt
=> Add compliance-john.top

spammers.txt
=> Add chcu.net

spammers.txt
socialtrade.biz - More Info: https://www.change.org/p/ministry-of-corporate-affairs-stop-fraud-companies-who-grab-the-people-money
=> Add Referrer Spammer

spammers.txt
=> Add 3-letter-domains.net

spammers.txt
=> Add mockupui.com

spammers.txt
=> Add aviav.co

spammers.txt
=> Add aviav.eu

spammers.txt
=> Add aviav.ru

spammers.txt
=> Add centrdebut.ru

spammers.txt
=> Add авиав.рф

spammers.txt
134.249.74.95 - - [15/Nov/2016:03:20:15 -0800] "GET / HTTP/1.1" 200 2623 / "http:// telegramdownload10. com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322) NS8/0.9.6" 0
134.249.74.95 - - [15/Nov/2016:03:20:16 -0800] "GET / HTTP/1.1" 200 2623 / "http:// telegramdownload10 .com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322) NS8/0.9.6" 0
134.249.74.95 - - [15/Nov/2016:03:20:17 -0800] "GET / HTTP/1.1" 200 2623 / "http:// telegramdownload10 .com/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322) NS8/0.9.6" 0
=> Add telegramdownload10.com

spammers.txt
134.249.74.95 - - [13/Nov/2016:14:22:31 -0800] "GET /  HTTP/1.1" 200 2623 /  "http:// whatsappdownload10 .com/whatsapp-on-ipad/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)" 0
134.249.74.95 - - [13/Nov/2016:14:22:32 -0800] "GET /  HTTP/1.1" 200 2623 /  "http:// whatsappdownload10 .com/whatsapp-on-ipad/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)" 0 
134.249.74.95 - - [13/Nov/2016:14:22:33 -0800] "GET /  HTTP/1.1" 200 2623 /  "http:// whatsappdownload10 .com/whatsapp-on-ipad/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)" 0
=> Add whatsappdownload10.com

spammers.txt
104.28.11.91 - - [10/Nov/2016:00:03:55 +0100] "GET / HTTP/1.1" 403 1925 "http:// wechatdownload10 .com/wechat-on-pc.html" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.0" "-"
104.28.11.91 - - [10/Nov/2016:00:03:55 +0100] "GET / HTTP/1.1" 403 1925 "http:// wechatdownload10 .com/wechat-on-pc.html" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.0" "-"
=> Add wechatdownload10.com

spammers.txt
=> Add ukrup.com

spammers.txt
=> Add uhodzalijami.ru

spammers.txt
5.248.196.220 - - [11/Dec/2016:01:14:09 +0100] "GET /about-us/ HTTP/1.1" 200 25170 "http:// tri-slona. org/category/christmas" "Opera/9.0 (Windows NT 5.1; U; en)"
5.248.196.220 - - [11/Dec/2016:01:14:09 +0100] "GET /about-us/ HTTP/1.1" 200 25170 "http:// tri-slona. org/category/christmas" "Opera/9.0 (Windows NT 5.1; U; en)"
5.248.196.220 - - [11/Dec/2016:01:14:10 +0100] "GET /about-us/ HTTP/1.1" 200 25170 "http:// tri-slona. org/category/christmas" "Opera/9.0 (Windows NT 5.1; U; en)"
=> Add tri-slona.org

spammers.txt
=> Add scanmarine.info

spammers.txt
=> Add samolet.fr

spammers.txt
46.119.127.117 - - [16/Nov/2016:11:47:16 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// komputers-best. ru/" "Opera/7.60 (Windows NT 5.2; U)  [en] (IBM EVV/3.0/EAK01AG9/LE)"
=> Add komputers-best.ru

spammers.txt
46.119.127.117 - - [16/Nov/2016:11:47:16 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// pizda .lol/" "Opera/7.60 (Windows NT 5.2; U)  [en] (IBM EVV/3.0/EAK01AG9/LE)"
46.119.127.117 - - [16/Nov/2016:11:47:16 +0100] "GET /*/ HTTP/1.0" 301 235 "http:// pizda. lol/" "Opera/7.60 (Windows NT 5.2; U)  [en] (IBM EVV/3.0/EAK01AG9/LE)"
=> Add pizda.lol

spammers.txt
=> Add pearlisland.ru

spammers.txt
134.249.74.95 - - [10/Nov/2016:13:18:33 -0800] "GET / HTTP/1.1" 200 2623 / "http:// monarhs. info/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)" 0 
134.249.74.95 - - [10/Nov/2016:13:18:34 -0800] "GET / HTTP/1.1" 200 2623 / "http:// monarhs. info/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)" 0
=> Add monarhs.info

spammers.txt
=> Add matematikus.info

spammers.txt
=> Add farmingworm.com

spammers.txt
195.133.48.150 - - [08/Dec/2016:22:28:19 +0100] "HEAD / HTTP/1.1" 302 192 "http:// investzalog. ru/uslugi.php?id=9" "Mozilla/4.0 (compatible; MSIE4.00; Windows 2005)"
195.133.48.150 - - [09/Dec/2016:01:18:00 +0100] "HEAD / HTTP/1.1" 302 192 "http:// investzalog .ru/contact.php?id=5" "Mozilla/4.0 (compatible; MSIE4.00; Windows 2009)"
195.133.48.150 - - [09/Dec/2016:04:44:30 +0100] "HEAD / HTTP/1.1" 302 192 "http:// investzalog .ru/razdel.php?id=2" "Mozilla/4.0 (compatible; MSIE6.00; Windows 2003)"
=> Add investzalog.ru

spammers.txt
=> Add leboard.ru

spammers.txt
185.158.153.84 - - [07/Dec/2016:04:10:07 -0800] "HEAD / HTTP/1.1" 302 244 "http:// letto. by/divani-krovati/priamie-divani/kniga/divan_kniga_lagos" "Mozilla/7.0 (compatible; MSIE3.00; Windows 2008)"
185.158.153.28 - - [07/Dec/2016:04:09:45 -0800] "HEAD / HTTP/1.1" 302 244 "http:// letto. by/divani-krovati/divan_edid_seruy_valensia" "Mozilla/3.0 (compatible; MSIE2.00; Windows 2007)"
=> Add letto.by

spammers.txt
=> Add lider-zhaluzi.kiev.ua

spammers.txt
134.249.74.95 - - [12/Nov/2016:00:25:48 -0800] "GET / HTTP/1.1" 200 2623 / "http:// manuscript .su/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)" 0 
134.249.74.95 - - [12/Nov/2016:00:25:49 -0800] "GET / HTTP/1.1" 200 2623 / "http:// manuscript. su/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)" 0
134.249.74.95 - - [12/Nov/2016:00:25:50 -0800] "GET / HTTP/1.1" 200 2623 / "http:// manuscript. su/" "Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)" 0
=> Add manuscript.su

spammers.txt
193.124.131.168 - - [07/Dec/2016:03:46:34 -0800] "HEAD / HTTP/1.1" 302 244 "http:// marblestyle .ru/podokonniki-iz-oniksa" "Mozilla/8.0 (compatible; MSIE3.00; Windows 2007)"
193.124.131.168 - - [07/Dec/2016:07:27:09 -0800] "HEAD / HTTP/1.1" 302 244 "http:// marblestyle. ru/podokonniki-iz-oniksa" "Mozilla/3.0 (compatible; MSIE2.00; Windows 2005)"
193.124.131.168 - - [07/Dec/2016:11:09:47 -0800] "HEAD / HTTP/1.1" 302 244 "http:// marblestyle. ru/podokonniki-iz-granita" "Mozilla/2.0 (compatible; MSIE6.00; Windows 2005)"
=> Add marblestyle.ru

spammers.txt
195.133.48.150 - - [09/Dec/2016:22:49:40 +0100] "HEAD / HTTP/1.1" 302 192 "http:// dividendo .ru/163-promezhutochnye-dividendy-vtb-2016.html" "Mozilla/4.0 (compatible; MSIE2.00; Windows 2008)"
=> Add dividendo.ru

spammers.txt
195.133.48.150 - - [09/Dec/2016:12:04:08 +0100] "HEAD / HTTP/1.1" 302 192 "http:// tendergrupp. ru/" "Mozilla/7.0 (compatible; MSIE7.00; Windows 2002)"
195.133.48.150 - - [09/Dec/2016:15:43:06 +0100] "HEAD / HTTP/1.1" 302 192 "http:// tendergrupp .ru/" "Mozilla/3.0 (compatible; MSIE2.00; Windows 2004)"
195.133.48.150 - - [09/Dec/2016:19:25:09 +0100] "HEAD / HTTP/1.1" 302 192 "http:// tendergrupp .ru/" "Mozilla/5.0 (compatible; MSIE2.00; Windows 2005)"
=> Add tendergrupp.ru

spammers.txt
195.133.48.150 - - [08/Dec/2016:11:26:13 +0100] "HEAD / HTTP/1.1" 302 192 "http:// stbgroup. ru/rst.aspx" "Mozilla/2.0 (compatible; MSIE6.00; Windows 2008)"
195.133.48.150 - - [08/Dec/2016:15:09:32 +0100] "HEAD / HTTP/1.1" 302 192 "http:// stbgroup. ru/rfc.aspx" "Mozilla/6.0 (compatible; MSIE2.00; Windows 2007)"
195.133.48.150 - - [08/Dec/2016:19:01:52 +0100] "HEAD / HTTP/1.1" 302 192 "http:// stbgroup. ru/rst.aspx" "Mozilla/8.0 (compatible; MSIE3.00; Windows 2003)"
=> Add stbgroup.ru

spammers.txt
=> Add sharebutton.io

spammers.txt
=> Update spammer.txt add google-liar.ru

spammers.txt
Started showing up in GA honeypot April 6th
=> Add track-rankings.online

spammers.txt
Both started showing up on our instances with a vengeance.
=> Add paidonlinesites.com & landoftracking.com

spammers.txt
Started showing up in GA honeypot April 25th.
=> Add gearcraft.us

spammers.txt
Started showing up in GA April 26th
=> Add piulatte.cz

spammers.txt
New referer spam domain. Seeing them in statcounter and google analytics.
=> added thesmartsearch.net

spammers.txt
Add foxweber.com. See issue 605.
=> Add foxweber.com

spammers.txt
Showing up in Piwik and GA starting on July 6th 2017
=> Add earn-from-articles.com

spammers.txt
=> Add emerson-rus.ru

spammers.txt
Found in WP Statistics logs. Some Russian site.
=> Add xn--d1aifoe0a9a.top (подушки.top)

spammers.txt
Showing up in GA starting on Aug 1st
=> Add justkillingti.me

spammers.txt
Starting to show up in GA spam honeypots
=> Add 5-steps-to-start-business.com

spammers.txt
Spam that started showing up in August
=> Add gearsadspromo.club

spammers.txt
Started showing up in GA honeypot at beginning of August
=> Add needtosellmyhousefast.com

spammers.txt
Started showing up in GA in September
=> Add allmarketsnewdayli.gdn

spammers.txt
BS CickBank referrer spam. Started showing up in September
=> Add obsessionphrases.com

spammers.txt
Spam domain started showing up in referrer spam honeypot in September
=> Add f1nder.org

spammers.txt
Referrer spam showing up on honeypot
=> Add seojokes.net

spammers.txt
Started showing up in GA honeypot in September 20-ish
=> Add rapidsites.pro

spammers.txt
spam showing up in honeypot starting in late September
=> Add isotoner.com

spammers.txt
Referrer spam that started showing up mid September
=> Add realresultslist.com

spammers.txt
Referrer URL links to a fake blog style content spam site.
=> Added bedroomlighting.us

spammers.txt
I received an email from the CTO of this website. I'm open to removing it as it does seem this website might have been mistakenly added/blocked.
The email:
Hello, I am CTO of vc — big russian media about business
Recently we've noticed that we became a victim of a ​person who spammed many sites with our referrer because of our article about him https://vc.ru/21679-google-russian-spammer [rus].
We never used referrer spam and as I know this person stops ​doing this with our referrer, so could you please remove our domain vc.ru from your repository.
​Thank you
-- 
Ilya Chekalskiy
Chief Technology Officer at CMTT
=> Remove vc.ru

spammers.txt
Referrer originates from a spamdexing site.
=> Added 3waynetworks.com

spammers.txt
=> Add uptime-[as|eu|us].net

spammers.txt
Started showing up on logs Jan 4th.
=> Add theautoprofit.ml

spammers.txt
=> Added bsell.ru

spammers.txt
=> Added luton-invest.ru

spammers.txt
=> Added xn----7sbabm1ahc4b2aqff.su

spammers.txt
=> Added eko-gazon.ru

spammers.txt
=> Added prodaemdveri.com

spammers.txt
=> Added dienai.ru

spammers.txt
=> Added teplohod-gnezdo.ru

spammers.txt
=> Added loveorganic.ch

spammers.txt
=> Added betterhealthbeauty.com

spammers.txt
=> Added magnetic-bracelets.ru

spammers.txt
=> Added deart-13.ru

spammers.txt
=> Added podemnik.pro

spammers.txt
=> Added komp-pomosch.ru

spammers.txt
=> Added intex-air.ru

spammers.txt
=> Added zdm-auto.com

spammers.txt
=> Added infodocsportal.com

spammers.txt
=> Added kabinet-online-vtb.ru

spammers.txt
=> Added svetoch.moscow

spammers.txt
=> Added avtovykup.kz

spammers.txt
=> Added remkompov.ru

spammers.txt
=> Added artpaint-market.ru

spammers.txt
=> Added xn----itbbudqejbfpg3l.com

spammers.txt
=> Added zdorovie-nogi.info

spammers.txt
=> Added healbio.ru

spammers.txt
=> Added incitystroy.ru

spammers.txt
=> Added osteochondrosis.ru

spammers.txt
=> Added auto-kia-fulldrive.ru

spammers.txt
=> Added 12u.info

spammers.txt
=> Added biplanecentre.ru

spammers.txt
=> Added club-lukojl.ru

spammers.txt
=> Added sp-laptop.ru

spammers.txt
=> Added workius.ru

spammers.txt
=> Added zahvat.ru

spammers.txt
=> Added tsatu.edu.ua

spammers.txt
=> Added podseka1.ru

spammers.txt
=> Added kabinet-tinkoff.ru

spammers.txt
=> Added kabinet-ttk.ru

spammers.txt
=> Added kabinet-click-alfabank.ru

spammers.txt
=> Added kabinet-my-pochtabank.ru

spammers.txt
=> Added inform-ua.info

spammers.txt
=> Added inet-shop.su

spammers.txt
with
LC_ALL=C sort -uf -o spammers.txt spammers.txt
=> Sort the spammers and remove duplicates

spammers.txt
=> Add skinali.photo-clip.ru

spammers.txt
=> Add goodhumor24.com

spammers.txt
=> Add autoblog.org.ua

spammers.txt
=> Add spb-scenar.ru

spammers.txt
=> Add metallo-konstruktsii.ru

spammers.txt
=> Add kerch.site

spammers.txt
=> Add sundrugstore.com

spammers.txt
=> Add store-rx.com

spammers.txt
=> Add popugaychiki.com

spammers.txt
=> Add incomekey.net

spammers.txt
=> Add office2web.com

spammers.txt
=> Add xn--80aaajkrncdlqdh6ane8t.xn--p1ai

spammers.txt
=> Add unlimitdocs.net

spammers.txt
=> Add documentsite.net

spammers.txt
=> Add picturesmania.com

spammers.txt
=> Add docsarchive.net

spammers.txt
=> Add univerfiles.com

spammers.txt
=> Add documentbase.net

spammers.txt
=> Add edudocs.net

spammers.txt
=> Add msu.kharlov.ua

spammers.txt
=> Add xn----7sbabn5abjehfwi8bj.xn--p1ai

spammers.txt
=> Add pornohd1080.online

spammers.txt
=> Add game300.ru

spammers.txt
=> Add dermatovenerologiya.com

spammers.txt
=> Add ek-invest.ru

spammers.txt
=> Add laminat.com.ua

spammers.txt
=> Add docsportal.net

spammers.txt
=> Add shnyagi.net

spammers.txt
=> Add yaderenergy.ru

spammers.txt
=> Add vzheludke.com

spammers.txt
=> Add xn-----7kcaaxchbbmgncr7chzy0k0hk.xn--p1ai

spammers.txt
=> Add housemilan.ru

spammers.txt
=> Add modforwot.ru

spammers.txt
=> Add hard-porn.mobi

spammers.txt
=> Add vaderenergy.ru

spammers.txt
=> Add documentserver.net

spammers.txt
=> Add fanoboi.com

spammers.txt
=> Add souvenirua.com

spammers.txt
=> Add vzubkah.com

spammers.txt
=> Add pornoplen.com

spammers.txt
=> Add moinozhki.com

spammers.txt
Showed up in my GA: 10 users, 0 mins.
=> Add bestofferhddeed.info

spammers.txt
=> Add getadsincomely.info

spammers.txt
=> Add dawlenie.com

spammers.txt
Add seoservices2018.com in proper alphabetical order.
=> Add seoservices2018.com

spammers.txt
=> Add bpro1.top

spammers.txt
=> Add medicineseasybuy.com

spammers.txt
=> Add manimpotence.com

spammers.txt
=> Add rulate.ru

spammers.txt
=> Add udav.net

spammers.txt
=> Add 03e.info

spammers.txt
=> Add metallosajding.ru

spammers.txt
=> Add blog100.org

spammers.txt
=> Add infektsii.com

spammers.txt
=> Add impotentik.com

spammers.txt
=> Add resell-seo-services.com

spammers.txt
=> Add technika-remont.ru

spammers.txt
=> Add porno-chaman.info

spammers.txt
=> Add xn----8sblgmbj1a1bk8l.xn----161-4vemb6cjl7anbaea3afninj.xn--p1ai

spammers.txt
=> Add rent2spb.ru

spammers.txt
=> Add xn-----6kcamwewcd9bayelq.xn--p1ai

spammers.txt
=> Add moneyzzz.ru

spammers.txt
=> Add xn----ctbigni3aj4h.xn--p1ai

spammers.txt
=> Add viagra-soft.ru

spammers.txt
=> Add dosugrostov.site

spammers.txt
=> Add xn----8sbarihbihxpxqgaf0g1e.xn--80adxhks

spammers.txt
=> Add allergija.com

spammers.txt
=> Add sladkoevideo.com

spammers.txt
=> Add ask-yug.com

spammers.txt
=> Add pornoelita.info

spammers.txt
=> Add ruspoety.ru

spammers.txt
=> Add purchasepillsnorx.com

spammers.txt
=> Add sportwizard.ru

spammers.txt
=> Add ukrainian-poetry.com

spammers.txt
=> Add bezprostatita.com

spammers.txt
=> Add modnie-futbolki.net

spammers.txt
=> Add xn----ctbbcjd3dbsehgi.xn--p1ai

spammers.txt
=> Add russian-translator.com

spammers.txt
=> Add supermama.top

spammers.txt
=> Add top-l2.com

spammers.txt
=> Add x5market.ru

spammers.txt
=> Add money7777.info

spammers.txt
=> Add snegozaderzhatel.ru

spammers.txt
=> Add poiskzakona.ru

spammers.txt
=> Add avtointeres.ru

spammers.txt
=> Add artdeko.info

spammers.txt
=> Add aerodizain.com

spammers.txt
=> Add yes-com.com

spammers.txt
Showing up in GA since Aug 27th
=> Add autoseo-service.org

spammers.txt
=> Add kakablog.net

spammers.txt
=> Add lider82.ru

spammers.txt
=> Add sribno.net

spammers.txt
Redirect to www.xtrafficplus.com
=> Add kevblog.top

spammers.txt
=> Add xn--e1aaajzchnkg.ru.com

spammers.txt
Showing up in Google Analytics starting in Oct 2018
=> Add get-seo-help.com

spammers.txt
Redirect to the blacklisted "xtrafficplus.com
=> Add flyblog.xyz

spammers.txt
Redirect to the blacklisted "xtrafficplus.com
=> Add blog2019.xyz

spammers.txt
Add:
8-best-seo.com
9-best-seo.com
=> Add 8 and 9-best-seo.com

spammers.txt
Showing up in GA starting in Dec 2018
=> Add promotion-for99.com

spammers.txt
Redirects to the blacklisted xtrafficplus.com
=> Add dailyseo.xyz

spammers.txt
=> Add bestfortraders.com

spammers.txt
=> Add videotop.biz

spammers.txt
=> Add svensk-poesi.com

spammers.txt
=> Add hit-kino.ru

spammers.txt
=> Add rus-lit.com

spammers.txt
=> Add jav-fetish.site

spammers.txt
=> Add serialsx.ru

spammers.txt
=> Add okoshkah.com

spammers.txt
=> Add onlinewot.ru

spammers.txt
=> Add eurocredit.xyz

spammers.txt
=> Add tamada69.com

spammers.txt
=> Add drev.biz

spammers.txt
=> Add arabic-poetry.com

spammers.txt
=> Add wakeupseoconsultant.com

spammers.txt
=> Add moyparnik.com

spammers.txt
=> Add inmoll.com

spammers.txt
=> Add kakadu-interior.com.ua

spammers.txt
=> Add ege-essay.ru

spammers.txt
=> Add sssexxx.net

spammers.txt
=> Add pornhive.org

spammers.txt
=> Add zagadki.in.ua

spammers.txt
=> Add su1ufa.ru

spammers.txt
=> Add bin-brokers.com

spammers.txt
=> Add automobile-spec.com

spammers.txt
=> Add vezdevoz.com.ua

spammers.txt
=> Add javcoast.com

spammers.txt
=> Add narosty.com

spammers.txt
=> Add avcoast.com

spammers.txt
Found in logs of a German design freelancer. Site is a porn site, definitely not related.
=> Add 8xv8.com

spammers.txt
Found in logs of a German design freelancer. Site is about anabolics, not related in any way.
=> Add anabolics.shop

spammers.txt
Found in logs of a German design freelancer. Site is a Russian stock image site. Not related in any way.
=> Add artclipart.ru

spammers.txt
Found in logs of a German design freelancer. Russian beauty tricks not related in any way.
=> Add beauty-lesson.com

spammers.txt
Found in logs of a German design freelancer. Russian site definitely not related.
=> Add bitcoin-ua.top

spammers.txt
Found in logs of German freelancer. Viagra site not related in any way.
=> Add buypillsonline24h.com

spammers.txt
Found in logs of German design freelance. English cat site not related in any way.
=> Add cattyhealth.com

spammers.txt
Found in logs of German freelancer. English site not related in any way.
=> Add cheappills24h.com

spammers.txt
=> Add mrbojikobi4.biz

spammers.txt
=> Add vseigru.one

spammers.txt
Found in the logs of a German design freelancer. Poetry site is not related in any way.
=> Add deutsche-poesie.com

spammers.txt
Found in the logs of a German design freelancer. Russian porn site not related in any way.
=> Add dojki-devki.ru

spammers.txt
Found in the logs of a German freelancer. Russian porn site not related in any way.
=> Add doxysexy.com

spammers.txt
Found in the logs of a German freelancer. Drug store not related in any way.
=> Add drugstoreforyou.com

spammers.txt
=> Add englishtopic.ru

spammers.txt
Started showing up in Google Analytics 1/23/19.
=> Add autoseotips.com

spammers.txt
Found in logs from German freelancer. nginx install page!?
=> Add expediacustomerservicenumber.online

spammers.txt
Found in logs from German design freelancer. Russian site is not related in any way.
=> Add fialka.tomsk.ru

spammers.txt
=> Add gidonline.one

spammers.txt
=> Add iskussnica.ru

spammers.txt
Found in logs of German freelancer. Chinese porn site not related in any way.
=> Add jav-fetish.com

spammers.txt
Found in logs of German freelancer. Kazakh site not related in any way.
=> Add kazlenta.kz

spammers.txt
=> Add kinostar.online

spammers.txt
=> Add migronis.com

spammers.txt
Found in logs of German freelancer. Russian porn site not related in any way.
=> Add mnogabukaff.net

spammers.txt
=> Add natali-forex.com

spammers.txt
Found in logs of German freelancer. Site not related in any way.
=> Add painting-planet.com

spammers.txt
Found in logs of German freelancer. Russian porn site not related in any way.
=> Add pornobest.su

spammers.txt
Found in logs of German freelancer. Russian porn site not related in any way.
=> Add pornoslave.net

spammers.txt
=> Add russkie-sochineniya.ru

spammers.txt
Found in logs of German freelancer. Porn site not related in any way.
=> Add s-forum.biz

spammers.txt
=> Add shopfishing.com.ua

spammers.txt
=> Add sowhoz.ru

spammers.txt
=> Add sta-grand.ru

spammers.txt
=> Add stroi-24.ru

spammers.txt
=> Add sweet.tv

spammers.txt
=> Add ukrtvory.in.ua

spammers.txt
=> Add vector.peskostryi.ru

spammers.txt
Reverts matomo-org/referrer-spam-blacklist#1051
=> Revert "Add vector.peskostryi.ru"

spammers.txt
Found in logs of German freelancer. Russian porn site not related in any way.
=> Add x-lime.com

spammers.txt
=> Add beclean-nn.ru

spammers.txt
=> Add spain-poetry.com

spammers.txt
=> Add mydoctorok.ru

spammers.txt
=> Add draniki.org

spammers.txt
=> Add shtaketniki.ru

spammers.txt
=> Add medbrowse.info

spammers.txt
Started showing up in GA 1/30/19.
=> Add backlinks-fast-top.com

spammers.txt
=> Add rutor.group

spammers.txt
=> Add vpdr.pl

spammers.txt
Found in logs of a German freelancer. Marine related site not related in any way.
=> Add marinetraffic.com

spammers.txt
=> Add infogame.name

spammers.txt
=> Add javlibrary.cc

spammers.txt
=> Add francaise-poesie.com

spammers.txt
=> Add mamylik.ru

spammers.txt
=> Add piluli.info

spammers.txt
Showing up in Google Analytics 2/6
=> Add your-good-links

spammers.txt
Showing up in GA starting on 2/8/19
=> Add ai-seo-services.com

spammers.txt
=> Add veles.shop

spammers.txt
=> Add torrentgamer.net

spammers.txt
=> Add top10-online-games.com

spammers.txt
=> Add aitiman.ae

spammers.txt
=> Add uginekologa.com

spammers.txt
Redirects to the blocked xtrafficplus.com
=> Add blog2019.top

spammers.txt
=> Add pornosemki.info

spammers.txt
=> Add xn----btbdvdh4aafrfciljm6k.xn--p1ai

spammers.txt
=> Add credit.co.ua

spammers.txt
=> Add 03p.info

spammers.txt
Showing up in GA starting in March 2019
=> Add yes-do-now.com

spammers.txt
=> Add vzubah.com

spammers.txt
=> Add naturalpharm.com.ua

spammers.txt
=> Add supermodni.com.ua

spammers.txt
=> Add sexuria.net

spammers.txt
=> Add php-market.ru

spammers.txt
Showing up in GA starting on 3/15
=> Add coverage-my.com

spammers.txt
Showing up in GA starting on 4/2/19
=> Add 2-go-now.xyz

spammers.txt
Showing up in GA starting on 4/4/19
=> Add 2-easy.xyz

spammers.txt
=> Add raymondblog.top

spammers.txt
New Spam URL found today in my stats.
=> added teresablog.top

spammers.txt
=> Add albuteroli.com

spammers.txt
Thousands of spam referrals per day to our site from various subdomains
=> adding w2mobile-za.com

spammers.txt
=> Add lowpricesiterx.com

spammers.txt
=> Add edmed-sonline.com

spammers.txt
Mainly for transport.dspautomations.com
=> Block dspautomations.com

spammers.txt
Mainly for auto.mwductwork.com
=> Block mwductwork.com

spammers.txt
=> Block goodbyecellulite.ru

README.md
as mentioned in https://github.com/matomo-org/referrer-spam-blacklist/issues/1105#issuecomment-481403383
=> Explain to create pull requests (not issues)

spammers.txt
=> Add 033nachtvandeliteratuur.nl

spammers.txt
=> Add tammyblog.online

spammers.txt
=> Add barbarahome.top

spammers.txt
=> Add rachelblog.online

spammers.txt
Added new traffic referral spam site; origin http://trafers.com
=> Add trafers.com

spammers.txt
=> Add darleneblog.online

spammers.txt
=> Add marjorieblog.online

spammers.txt
=> Add veronicablog.top

spammers.txt
=> Add hexometer.com

spammers.txt
=> Add progressive-seo.com

spammers.txt
=> Add constanceonline.top

spammers.txt
=> Add nancyblog.top

spammers.txt
* Adds 52 spammers to the list. Creating a separate PR for each of them would be too time consuming; please consider this PR as a whole instead.
* Corrects whitespace issue with entry for `your-good-links.com`
=> Added more spammers to the list

spammers.txt
=> Add deirdre.top

spammers.txt
=> Add deniseconnie.top

spammers.txt
Submission from callaloo #1168 . 
Thank you
=> Add bottraffic4free.host

spammers.txt
We keep being hit by new referrer spammers...
=> Added more spammers

spammers.txt
=> Add reginanahum.top

spammers.txt
=> Add ninacecillia.top

spammers.txt
=> Add maxinesamson.top

spammers.txt
Some of these are, one more, variations on the same domain names. Would you consider the use wildcards or some such?
=> More spammers, again

spammers.txt
=> Add blogking.top

spammers.txt
Appearing in my Matomo reports. Redirecting to Xtraffic+
=> Add denisecarey.top

spammers.txt
Appearing in my Matomo reports. Redirecting to Xtraffic+
=> Add elizabethbruno.top

spammers.txt
=> Add adelachrist.top

spammers.txt
=> Add greentechsy.com

spammers.txt
=> Add ingramreed.xyz

spammers.txt
=> Add janemill.xyz

spammers.txt
=> Add sabinablog.xyz

spammers.txt
=> Add martinahome.xyz

spammers.txt
=> Add ptfic.org

spammers.txt
Lots of referrer spam with a link to articles/leaked-crazy-new-adidas-preserved-pair-packaging-revealed/
=> Add sneakerfreaker.com

spammers.txt
=> Add leddjc.net

spammers.txt
=> Add oudallas.net

spammers.txt
kosunnyclub.com
zhcsapp.net
skipped in favor of other PR: leddjc.net
=> add 2 new domains

spammers.txt
=> Add commentag.com

spammers.txt
=> Add estdj.com

spammers.txt
This is the continuation of #1198 with `marketwatch.com` removed, and amend with another batch. This makes for a total of 54 additions.
I have gone over the data once more, and believe all these domains to warrant inclusion. However, if needed, I can easily amend my PR. There should be no need to open a new one.
=> More spammers

spammers.txt
=> Add deryie.com

spammers.txt
Just got a bunch of spam from websitebottraffic.host
=> Add websitebottraffic.host

spammers.txt
=> Add dreams-works.net

spammers.txt
=> Add nwrcz.com

spammers.txt
Many of these are variants of domains that already existed in the blacklist.
=> Added new spammer variant domains

spammers.txt
Saw this in my referrer traffic list in Matomo coming out of China.
=> Add brooklynsays.com

spammers.txt
Saw this in my referrer list in Matomo coming out of China.
=> Add andrewancheta.com

spammers.txt
Saw this in my referral list in Matomo.
=> Add nyinfo.org

spammers.txt
Saw this in my referral list coming out of Germany.
=> Add eduardoluis.com

spammers.txt
Saw this in my referral list in Matomo coming out of China.
=> Add ideayz.com

spammers.txt
Saw this in my referral list in Matomo.
=> Add popelina.com

spammers.txt
Saw in referral traffic in Matomo.
=> Add iceton.net

spammers.txt
=> Add mybestoffers.club

spammers.txt
=> Add batietiket.com

spammers.txt
Noticed this on several of my sites and it looks like a referrer spam to me. No links there to my sites and all traffic is very low quality (0.00 time on site).
=> Adding mycollegereview.com

spammers.txt
Saw hundreds of accesses to this url in my Matomo logs from different ips mostly coming from Viet nam
=> Added phimmakinhdi.com

spammers.txt
=> Add eecz.org

spammers.txt
=> Add darcysassoon.top

spammers.txt
=> Add aimiot.net

spammers.txt
=> Add meroyharte.top

spammers.txt
=> Add immobilieralgerie.net

spammers.txt
=> Add michellblog.online

spammers.txt
=> Add kevinsnow.online

spammers.txt
=> Add niuting.org

spammers.txt
=> Add jyrxd.com

spammers.txt
=> Add maofengjx.com

spammers.txt
Website of a domain name registrar found in the logs of a website of a mathematics french tutor.
=> Add 0-0.fr

spammers.txt
=> Add semxiu.com

spammers.txt
=> Add bavsac.com

spammers.txt
=> Add rrutw.com

spammers.txt
redirected to www.gammatraffic.com
=> added bottraffic.live

spammers.txt
redirected to www.gammatraffic.com
=> added bot-traffic.icu

spammers.txt
added bot-traffic.xyz & trafficbot.life and their redirect target gammatraffic.com
=> added bot-traffic.xyz & trafficbot.life

spammers.txt
=> Add doreenblog.online

spammers.txt
=> Add vanessablog.online

spammers.txt
=> Add wandamary.online

spammers.txt
=> Add eets.net

spammers.txt
Please add senacertificados.co redirects to fill.dontkinhooot.tw and makes a series of redirects afterwards.
=> Plesase add senacertificados.co

spammers.txt
=> Add faithe.top

spammers.txt
=> Add bradleylive.xyz

spammers.txt
=> Add kellyonline.xyz

spammers.txt
=> Add primoblog.xyz

spammers.txt
=> Add johnnyhaley.top

spammers.txt
=> Add joyceblog.top

spammers.txt
=> Add sarahmilne.top

spammers.txt
redirects to the already added gammatraffic.com
=> Added yourtraffic.club

spammers.txt
=> Add aucoinhomes.com

spammers.txt
This is a confirmed referrer spammer.
=> added botttraffic999.xyz to spammers list

spammers.txt
=> Add aoul.top

spammers.txt
=> Add manwang.net

spammers.txt
=> Add xmnb.net

spammers.txt
=> Add rczhan.com

spammers.txt
=> Add hsoutdoor.com

spammers.txt
=> Add czcedu.com

spammers.txt
=> Add amatocanizalez.net

spammers.txt
=> Add gcmx.net

spammers.txt
=> Add qxnr.net

spammers.txt
=> Add arpe.top

spammers.txt
=> bottraffic143.xyz

spammers.txt
=> trafficstudio.club

spammers.txt
=> Add heeha.net

spammers.txt
=> Add blognet.top

spammers.txt
=> Add tccp.xyz

spammers.txt
=> semalt.net

spammers.txt
=> Add goldvaultmetals.com

spammers.txt
=> Add dailyblog.xyz

spammers.txt
=> Add klfd.net

spammers.txt
=> Add iblogpress.xyz

spammers.txt
Another xtraffic redirect site
=> Add lsitenonrepeat.com

spammers.txt
=> Add socialine.net

spammers.txt
=> Add glktfw.net

spammers.txt
=> Add hilaryblog.top

spammers.txt
=> Add goodcoffeepremium.com

spammers.txt
=> Add kimblog.top

spammers.txt
=> Add erinhome.xyz

spammers.txt
=> Add danhale.xyz

spammers.txt
=> Add katrd.xyz

spammers.txt
=> Add ucban.xyz

spammers.txt
=> Add hrtonline.xyz

spammers.txt
Add trafficdrive.club it was found in a few of my clients analytics account
=> Add some Spam Sites

spammers.txt
I received many bot clicks from this one
=> Add bottraffic329.xyz

spammers.txt
I received many bot clicks from this one
=> Add getbottraffic4free.xyz

spammers.txt
=> Add goyua.xyz

spammers.txt
=> Add nanwar.xyz

spammers.txt
=> Add qtrstar.xyz

spammers.txt
=> Add mtras.xyz

spammers.txt
=> Add atoblog.online

spammers.txt
=> Add mossiemckenzie.shop

spammers.txt
=> Add hugblog.xyz

spammers.txt
Redirects to blacklisted semalt.com
=> Add seo-traffic.xyz

spammers.txt
=> Add shoppinglocation.com

spammers.txt
=> Add judyandsimon.com

spammers.txt
=> Add residualforlife.com

spammers.txt
=> Add thegreensociety.net

spammers.txt
=> Add nutriwestncahi.com

spammers.txt
=> Add epcpolo.com

spammers.txt
=> Add 100+ .xyz domains

spammers.txt
=> Add emicef.com

spammers.txt
=> Add singularwebs.net

spammers.txt
=> Add nfocusdriver.com

spammers.txt
redirects to https://www.xtraffic.plus/
=> Add www.chomexun.com

spammers.txt
=> Add chomexun.com

spammers.txt
redirects to www.xtraffic.plus
=> Add madisonclothingny.com

spammers.txt
=> Add britneyblog.online

spammers.txt
=> Add blancablog.online

spammers.txt
Redirects to blacklisted xtraffic.plus
=> Add ericshome.store

spammers.txt
=> Add elainasblog.xyz

spammers.txt
=> Add kendrablog.online

spammers.txt
=> Add aimeesblog.xyz

spammers.txt
A spammy agency we notices in our referals.
=> Add urlumbrella.com

spammers.txt
=> Add bonniesblog.online

spammers.txt
=> Add jacblog.xyz

spammers.txt
=> Add harpro.net

spammers.txt
=> Add besthatcheries.com

spammers.txt
=> Add wptraffic.xyz

spammers.txt
=> Add startraffic.online

spammers.txt
=> Add abaiak.com

spammers.txt
=> Add hiwpro.xyz

spammers.txt
=> Add jackonline.store

spammers.txt
=> Add sjmsw.net

spammers.txt
=> Add davilaonline.shop

spammers.txt
=> Add urbanblog.shop

spammers.txt
=> Add tommysautomotivecare.com

spammers.txt
=> Add erias.xyz

spammers.txt
=> Add xtrafficplus.xyz

spammers.txt
=> Add blogorganictraffic.shop

spammers.txt
Seeing tens of thousands of requests like this one:
=> Add 84lv.com

spammers.txt
Seeing tens of thousands of requests like this one:
=> Add 16lv.com

spammers.txt
Seeing tens of thousands of requests from this domain
Similar as #1413. I can provide additional screenshots if desired.
=> Add 1-88.vip

spammers.txt
Seeing tens of thousands of requests from this domain
Same as #1413. I can provide additional screenshots if desired.
=> Add top8.co

spammers.txt
Seeing tens of thousands of requests from this domain
Same as #1413. I can provide additional screenshots if desired.
=> Add tip8.co

spammers.txt
=> Add urbanchr.online

spammers.txt
=> Add blogtraffic.shop

spammers.txt
=> Add feiacmr.shop

spammers.txt
=> Add kaircm.shop

spammers.txt
=> Add arcarticle.online

spammers.txt
Promises "Get organic traffic the easy way".
=> Add uctraffic.com

spammers.txt
Redirects to the blocklisted uctraffic.com
=> Add ialgramer.shop

spammers.txt
Redirects to the blocklisted uctraffic.com
=> Add hagirkblog.space

spammers.txt
=> Add minghaimuyuan.net

spammers.txt
=> Add novalskincare.net

spammers.txt
=> Add ttechno.net

spammers.txt
=> Add newsfj.net

spammers.txt
=> Add alguiblog.online

spammers.txt
Redirects to spam site https://www.uctraffic.com
=> Add meuikcr.online

spammers.txt
Redirects to known spam site: https://www.uctraffic.com
=> Add ciarustde.online
